services:
  codex:
    image: codex
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
    ports:
      - "3000:3000"
    env_file:
      - .env.local
